version: '3.8'

services:
  email-receiver:
    build:
      context: .
      dockerfile: Dockerfile
    image: email-receiver-api:latest
    container_name: email-receiver-app
    ports:
      - "3000:3000"
    environment:
      # 基础配置
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      
      # API 配置
      - API_PREFIX=/email-receiver-api
      - CORS_ORIGIN=https://bridge.yunc.tech
      
      # 日志配置
      - LOG_LEVEL=info
      - LOG_FILE_PATH=logs/app.log
      - ERROR_LOG_FILE_PATH=logs/error.log
      
      # 数据路径
      - DATA_PATH=data
      - EMAILS_PATH=data/emails
      - INVOICES_PATH=data/invoices
      
      # 发票识别配置
      - INVOICE_CONFIDENCE_THRESHOLD=0.3
      - INVOICE_KEYWORD_SCORE_WEIGHT=0.4
      - INVOICE_SENDER_SCORE_WEIGHT=0.3
      - INVOICE_SUBJECT_SCORE_WEIGHT=0.3
      
      # IMAP 配置
      - IMAP_CONNECTION_TIMEOUT=10000
      - IMAP_AUTH_TIMEOUT=5000
      
      # 邮件处理配置
      - MAX_EMAILS_TO_FETCH=50
      - ENABLE_LOCAL_STORAGE=true
      
      # 敏感信息（生产环境中应通过 secrets 或外部环境变量传入）
      # - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      
    volumes:
      # 数据持久化
      - ./data:/app/data
      - ./logs:/app/logs
      
    # 如果需要使用 Docker secrets（推荐生产环境）
    # secrets:
    #   - email_password
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { hostname: 'localhost', port: 3000, path: '/api/health', timeout: 2000 }; const req = http.request(options, (res) => { if (res.statusCode === 200) process.exit(0); else process.exit(1); }); req.on('error', () => process.exit(1)); req.on('timeout', () => process.exit(1)); req.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - email-network
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  email-network:
    driver: bridge

volumes:
  # 如果需要使用 Docker 管理的卷而不是主机目录
  email-data:
    driver: local
  email-logs:
    driver: local